# TODO: this need some non-trivial refactoring...
Metrics/AbcSize:
  Max: 111

# TODO: this need some non-trivial refactoring...
Metrics/BlockNesting:
  Max: 5

# TODO: this need some non-trivial refactoring...
Metrics/ClassLength:
  Max: 450

# TODO: this need some non-trivial refactoring...
Metrics/CyclomaticComplexity:
  Max: 25

Metrics/LineLength:
  Max: 100

# TODO: this need some non-trivial refactoring...
Metrics/MethodLength:
  Max: 96

# TODO: this need some non-trivial refactoring...
Metrics/PerceivedComplexity:
  Max: 25

# Offense count: 5
Style/AccessorMethodName:
  Enabled: false

# align arrows:
# "foo"     => true
# "foo_bar" => false
Style/AlignHash:
  EnforcedHashRocketStyle: table

# no extra indentation for multiline function calls
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# no extra indentation for case
Style/CaseIndentation:
  IndentWhenRelativeTo: end

# Offense count: 29
Style/Documentation:
  Enabled: false

# disabled, unless should be used only in trailing form
Style/NegatedIf:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 6

# Offense count: 1
# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Style/PredicateName:
  Enabled: false

# use "raise" instead of "fail"
Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# def foo?
#   @foo
# end
Style/TrivialAccessors:
  AllowPredicates: true

